version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_1505Project
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: TPP_services_in_FCS
  version: "1.0"
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.siqa_1505.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQA_1505Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: project.siqa_1505.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_1505Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2057
- serviceName: project.siqa_1505.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_1505Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: project.siqa_1505.integrations:Sum
  packages:
  - name: SIQA_1505Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2057
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2057
- serviceName: project.siqa_1505.integrations:deepclonetest
  packages:
  - name: SIQA_1505Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2057
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2057
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2057
- serviceName: project.siqa_1505.integrations:tppdaf
  packages:
  - name: SIQA_1505Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: services:add3Ints
  packages:
  - name: TPP_services_in_FCS
    version: "1.0"
